# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fb35264c0ed6af92628ae8b861a856748dab202fea7a17127519c095c993b4d93b5b4d8fb347c77c208022c9d75cd4ccc6f17390a25830cabf2fda20b72ae9

test:
  secret_key_base: 42714d3bbf19aa8edcb05ffa7145e561ce9fa74bf8e3bca1d1881a1135e1652fc914b7b6c8bd86f6216061bbe14d7b92884f0da408f9751d4550dd065fe287b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
